# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Validate-Domain
version:      0.09
version_from: lib/Data/Validate/Domain.pm
installdirs:  site
requires:
    Net::Domain::TLD:              1.62
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
