--- #YAML:1.0
name:                Data-Validate-Domain
version:             0.08
abstract:            domain validation methods
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Net::Domain::TLD:              1.62
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Neil Neely <neil@neely.cx>
